name: Deploy to server 

on: push

jobs:
  first_job:
    runs-on: ubuntu-latest
    env:
      Perro: Arya
      Gato: Luna
    steps:  
      - name: "Primer Step"
        id: step_1
        run: echo "VARIABLE=chuchis" >> $GITHUB_OUTPUT
      - name: "Segundo Step"
        run: echo "hola $Perro y $Gato ${{steps.step_1.outputs.VARIABLE }}" #Use context a level Steps

  second_job:
    needs: first_job #Run Job sequentially , default run in parallel Jobs
    runs-on: ubuntu-latest
    if: ${{github.ref == 'refs/heads/main'}} ## Run if Job run in case that context be branch main
    
    steps:
    - name: "primer Step"
      run: echo "tik tok"
    - name: "segundo Step"
      run: df 